// <auto-generated />
using System;
using HumanResourcesManagementSystemFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResourcesManagementSystemFinal.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Account", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("EmployeeID")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.ChangeHistory", b =>
                {
                    b.Property<string>("LogID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("ActionType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangeByUserID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("char(5)");

                    b.Property<string>("RecordID")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.HasIndex("ChangeByUserID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ChangeHistory");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Department", b =>
                {
                    b.Property<string>("DepartmentID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.HasKey("DepartmentID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("PositionID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.LeaveRequest", b =>
                {
                    b.Property<string>("RequestID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("ApproverID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("LeaveType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerComment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Position", b =>
                {
                    b.Property<string>("PositionID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("JobDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("PositionID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.TimeSheet", b =>
                {
                    b.Property<string>("TimeSheetID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<double?>("ActualHours")
                        .HasColumnType("REAL");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<TimeSpan?>("TimeIn")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("TimeSheetID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.WorkContract", b =>
                {
                    b.Property<string>("ContractID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<string>("ContractType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("smalldatetime");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("money");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("smalldatetime");

                    b.HasKey("ContractID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("WorkContracts");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Account", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("HumanResourcesManagementSystemFinal.Models.Account", "EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleID");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.ChangeHistory", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Account", "Account")
                        .WithMany("ChangeHistories")
                        .HasForeignKey("ChangeByUserID");

                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", null)
                        .WithMany("ChangeHistories")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Department", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Employee", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.LeaveRequest", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverID");

                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Requester")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Approver");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.TimeSheet", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Employee")
                        .WithMany("TimeSheets")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.WorkContract", b =>
                {
                    b.HasOne("HumanResourcesManagementSystemFinal.Models.Employee", "Employee")
                        .WithMany("WorkContracts")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Account", b =>
                {
                    b.Navigation("ChangeHistories");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Employee", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ChangeHistories");

                    b.Navigation("LeaveRequests");

                    b.Navigation("TimeSheets");

                    b.Navigation("WorkContracts");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HumanResourcesManagementSystemFinal.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
